### PR TITLE
fix: log_gamma for numpy backend

### PR DESCRIPTION
**Pull request by andreinechaev**
there is no `numpy.math` module. I assume `scipy` should be used. 

also, while running PhiFlow notebooks, I noticed that there is another similar issue in `_backend.py`.

### CODE REVIEW

**Comment by andreinechaev** [comment]
@holl- updated the main branch, I aligned my changes with the same approach, to support legacy numpy

**Comment by holl-** [comment]
Good catch!
I've removed the `numpy.math` references in this here: https://github.com/tum-pbs/PhiML/commit/65e4e3059cfe5b6c0901321beda3d5909beb77d1

**Comment by andreinechaev** [comment]
> Good catch! I've removed the `numpy.math` references here: [65e4e30](https://github.com/tum-pbs/PhiML/commit/65e4e3059cfe5b6c0901321beda3d5909beb77d1)

thank you. 
P.S. It would be nice to improve the way you work with contributors to improve the community and the quality of your software.

**Comment by holl-** [comment]
Hey! Sorry if I offended you in some way, wasn't my intention.

We follow pep8 for the most part but with [some exceptions](https://github.com/tum-pbs/PhiML/blob/main/CONTRIBUTING.md).

**Comment by andreinechaev** [comment]
> Hey! Sorry if I offended you in some way, wasn't my intention.
> 
> We follow pep8 for the most part but with [some exceptions](https://github.com/tum-pbs/PhiML/blob/main/CONTRIBUTING.md).

nw, I wasn't offended, just rather surprised. I made a small PR to fix first numpy misuse, a few hours later you push a fix for it. I push another commit to fix another numpy misuse, a day later you push a fix for that too. 
Some might get discouraged from contribution.

**Comment by holl-** [comment]
Yeah, I think the first one was concurrent work. The reason I didn't just merge this PR is that it contains a lot of unrelated changes due to your auto-formatter being configured differently from mine. I still appreciate your contributions, though, as I wouldn't have found the second bug otherwise.👍

**Pull request closed without merging**
